version: '3'

volumes:
  pgdata:

services:
  api:
    build: .
    command: ["sh", "./scripts/start-runserver.sh"]
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    env_file:
      - django.env
    links:
      - database
    depends_on:
      - database

  database:
    image: postgres:alpine
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=teleclinic
